package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "python_interpreter_type"
)

constraint_value(
    name = "hermetic_python",
    constraint_setting = "python_interpreter_type",
)
